### ISSUE TITLE
Failed to execute command set

### ISSUE THREAD

**Issue by BoPeng** [dan-oak/zsh-jupyter-kernel#12]
Running `set` command for the first time is ok,

![image](https://user-images.githubusercontent.com/9889312/80290467-c3a4c680-870a-11ea-8b10-889648ef2a9d.png)

but then the kernel hangs when `set` is executed the second time.

![image](https://user-images.githubusercontent.com/9889312/80290486-d7e8c380-870a-11ea-97cc-c2559c277808.png)

**Comment by dan-oak** [comment]
Fixed in 3.4. Sorry for a long absence.
