### ISSUE TITLE
Making the the zsh kernel accessible across environments?

### ISSUE THREAD

**Issue by CriticalSci** [dan-oak/zsh-jupyter-kernel#13]
Hi there,

I'm trying to setup a few different conda environments containing kernels accessible from the Jupyter Lab in the base conda environment. When IPython and IR kernels are installed in different environments they can be installed by specifying `--user`, `--name` and `--display_name` making them available to Jupyter Lab in other environments such as the base environment.

However as far as I can see this is not possible with this zsh kernel. Is there an alternative way of doing this or am I missing something?

Many thanks!

**Comment by dan-oak** [comment]
done in [3.5.0](https://pypi.org/project/zsh-jupyter-kernel/3.5.0/)
sorry for _a slight delay_. life.
